import { useEffect } from "react";
import { Link } from "react-router-dom";
import NavBar from "../../components/NavBar/NavBar";
import { useLanguage } from "../../context/LanguageContext";
import { text } from "../../data/editorial";
import { captchaSiteKey, contactFormEnabled } from "../../lib/securityConfig";
import "../../components/ProjectStory/ProjectStory.css";
import "../profile/Profile.css";
import "./Privacy.css";
import { useStoragePreferences } from "../../context/StoragePreferencesContext";

const sections = [
  { title: text("Who is responsible", "Quem é responsável", "Quién es responsable"), body: text(
    "Christian Silva is responsible for the use of personal data in this portfolio. For privacy requests, contact christiansilva.dev@outlook.com. This notice describes the current implementation; it is not a claim of a completed legal certification.",
    "Christian Silva é responsável pelo uso de dados pessoais neste portfólio. Para solicitações de privacidade, use christiansilva.dev@outlook.com. Este aviso descreve a implementação atual; não representa uma certificação jurídica de conformidade.",
    "Christian Silva es responsable del uso de datos personales en este portafolio. Para solicitudes de privacidad, escribe a christiansilva.dev@outlook.com. Este aviso describe la implementación actual; no representa una certificación jurídica de cumplimiento.") },
  { title: text("Browsing and preferences", "Navegação e preferências", "Navegación y preferencias"), body: text(
    "You can read projects and articles without an account. Theme and language work without saving them; the storage controls let you choose whether to remember each on this browser. Valid preferences saved before these controls were introduced are preserved until you disable or clear them. New visitors do not save these preferences automatically. GitHub Pages and Supabase may process connection information, such as IP address and request logs, to deliver and protect their services.",
    "Você pode ler projetos e artigos sem criar uma conta. Tema e idioma funcionam sem serem salvos; os controles de armazenamento permitem escolher se cada um será lembrado neste navegador. Preferências válidas salvas antes destes controles são preservadas até você desativá-las ou limpá-las. Novos visitantes não salvam essas preferências automaticamente. GitHub Pages e Supabase podem tratar informações de conexão, como endereço IP e registros de requisições, para entregar e proteger seus serviços.",
    "Puedes leer proyectos y artículos sin crear una cuenta. Tema e idioma funcionan sin guardarse; los controles permiten elegir si recordar cada uno en este navegador. Las preferencias válidas guardadas antes de estos controles se mantienen hasta que las desactives o borres. Los nuevos visitantes no guardan estas preferencias automáticamente. GitHub Pages y Supabase pueden tratar información de conexión, como dirección IP y registros de solicitudes, para prestar y proteger sus servicios.") },
  { title: text("Account and authentication", "Conta e autenticação", "Cuenta y autenticación"), body: text(
    "Public registration remains available. When you create an account, your name and email are processed through Supabase Auth and the profile database. Passwords are sent over HTTPS to Supabase Auth and hashed by that service; this application does not keep password hashes. An authenticated session is persisted in browser storage until sign-out or removal of local data; server-side token validity is managed separately by Supabase. Do not use a shared device without signing out.",
    "O cadastro público permanece disponível. Ao criar uma conta, nome e e-mail são tratados pelo Supabase Auth e pelo banco de perfis. Senhas são enviadas por HTTPS ao Supabase Auth e transformadas em hash por esse serviço; esta aplicação não mantém hashes de senha. A sessão autenticada é persistida no armazenamento do navegador até o logout ou a remoção dos dados locais; a validade dos tokens no servidor é gerenciada separadamente pelo Supabase. Evite deixar uma sessão aberta em um dispositivo compartilhado.",
    "El registro público permanece disponible. Al crear una cuenta, nombre y correo se tratan mediante Supabase Auth y la base de perfiles. Las contraseñas se envían por HTTPS a Supabase Auth, que almacena sus hashes; esta aplicación no conserva hashes de contraseñas. La sesión se guarda en el navegador hasta cerrar sesión o borrar los datos locales; la validez de los tokens en el servidor se gestiona por separado en Supabase. No dejes una sesión abierta en un dispositivo compartido.") },
  { title: text("No behavioral analytics", "Sem análise comportamental", "Sin análisis de comportamiento"), body: text(
    "The application does not include advertising trackers or send its performance diagnostics to an analytics service. The optional performance panel stays on your device. This does not mean that hosting providers keep no operational logs. The pedal lab is a mathematical simulation and does not access hardware, camera or microphone.",
    "A aplicação não inclui rastreadores de publicidade nem envia seus diagnósticos de desempenho a um serviço de analytics. O painel opcional permanece no seu dispositivo. Isso não significa que os provedores de hospedagem não mantenham registros operacionais. O laboratório de pedais é uma simulação matemática e não acessa hardware, câmera ou microfone.",
    "La aplicación no incluye rastreadores publicitarios ni envía sus diagnósticos de rendimiento a un servicio de analytics. El panel opcional permanece en tu dispositivo. Esto no significa que los proveedores de alojamiento no conserven registros operativos. El laboratorio de pedales es una simulación matemática y no accede a hardware, cámara ni micrófono.") },
  { title: text("Providers and international processing", "Fornecedores e tratamento internacional", "Proveedores y tratamiento internacional"), body: text(
    "GitHub provides hosting; Supabase provides public content, authentication and profile storage, and relays contact requests when the form is enabled. The Supabase project is configured in West US (Oregon), United States. Brevo delivers enabled web-form messages; replies arrive at the portfolio owner's Outlook mailbox. Providers may process data outside Brazil. Applicable transfer safeguards and provider retention periods still need operational verification. External links open another service under its own privacy terms.",
    "GitHub fornece hospedagem; Supabase fornece conteúdo público, autenticação e armazenamento de perfis, e encaminha solicitações de contato quando o formulário está ativo. O projeto Supabase está configurado em West US (Oregon), Estados Unidos. O Brevo entrega mensagens enviadas pelo formulário ativo; as respostas chegam à caixa Outlook do responsável. Fornecedores podem tratar dados fora do Brasil. As garantias aplicáveis à transferência e os prazos de retenção ainda precisam de verificação operacional. Links externos levam a outro serviço, sujeito aos próprios termos.",
    "GitHub ofrece alojamiento; Supabase ofrece contenido público, autenticación y almacenamiento de perfiles, y transmite solicitudes de contacto cuando el formulario está activo. El proyecto Supabase está configurado en West US (Oregon), Estados Unidos. Brevo entrega los mensajes del formulario activo; las respuestas llegan al buzón Outlook del responsable. Los proveedores pueden tratar datos fuera de Brasil. Las garantías de transferencia y los plazos de conservación aún requieren verificación operativa. Los enlaces externos llevan a otros servicios y sus propios términos.") },
  { title: text("Retention and current limits", "Retenção e limites atuais", "Conservación y límites actuales"), body: text(
    "The current code does not automatically delete accounts or correspondence after a fixed period. Saved theme and language remain until disabled, removed through the storage panel, or cleared in browser settings. Retention periods and the lawful basis for each processing activity are being finalized with the operator; no automatic purge or fixed supplier-log deadline is promised. Previously published content can remain in static pages until a new deployment replaces it.",
    "O código atual não elimina automaticamente contas ou correspondências após um período fixo. Tema e idioma salvos permanecem até serem desativados, removidos pelo painel de armazenamento ou limpos nas configurações do navegador. Os prazos de retenção e a base legal de cada atividade estão em definição com o responsável; não há promessa de descarte automático nem de um prazo fixo para logs dos fornecedores. Conteúdo antes publicado pode permanecer nas páginas estáticas até que um novo deploy o substitua.",
    "El código actual no elimina automáticamente cuentas o correspondencia después de un plazo fijo. El tema e idioma guardados permanecen hasta desactivarse, borrarse en el panel o limpiarse en el navegador. Los plazos y la base legal de cada actividad se están definiendo con el responsable; no se promete borrado automático ni un plazo fijo para los registros de proveedores. El contenido publicado puede permanecer en páginas estáticas hasta un nuevo despliegue.") },
  { title: text("Your requests", "Suas solicitações", "Tus solicitudes"), body: text(
    "You can request confirmation of processing, access, correction and deletion where applicable, or ask about sharing and retention, by email with the subject “Privacy request”. Identity may need proportionate verification before account data are disclosed or deleted. This is a manual request channel, not an automatic account-deletion button. Never send a password, session token, authenticator secret or one-time code.",
    "Você pode solicitar confirmação de tratamento, acesso, correção e eliminação quando aplicável, ou perguntar sobre compartilhamento e retenção, por e-mail com o assunto “Solicitação de privacidade”. Pode ser necessária uma verificação proporcional de identidade antes de fornecer ou eliminar dados de uma conta. Este é um canal de solicitação manual, não um botão de exclusão automática. Nunca envie senha, token de sessão, chave de autenticador ou código de uso único.",
    "Puedes solicitar confirmación de tratamiento, acceso, rectificación y eliminación cuando corresponda, o preguntar sobre compartir y conservar datos, por correo con el asunto “Solicitud de privacidad”. Puede requerirse verificación proporcional de identidad antes de entregar o borrar datos de una cuenta. Este canal es manual, no un botón de eliminación automática. Nunca envíes contraseñas, tokens de sesión, claves de autenticador ni códigos de un solo uso.") },
];

export default function Privacy() {
  const { language } = useLanguage();
  const { openStorageSettings } = useStoragePreferences();
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); }, []);
  return <><NavBar /><main id="main-content" tabIndex={-1} className="editorial-page privacy-page">
    <header className="editorial-page-header"><p className="story-eyebrow">PRIVACY / 01</p>
      <h1>{text("Clear about your data.", "Clareza sobre seus dados.", "Claridad sobre tus datos.")[language]}</h1>
      <p>{text("Privacy notice · Updated September 28, 2026", "Aviso de privacidade · Atualizado em 28 de setembro de 2026", "Aviso de privacidad · Actualizado el 28 de septiembre de 2026")[language]}</p>
    </header>
    <div className="privacy-reading">
      <aside className="privacy-summary"><p className="story-eyebrow">{text("IN SHORT", "EM RESUMO", "EN RESUMEN")[language]}</p>
        <p>{text("Read without an account. Preferences stay local. Public registration is available. No advertising analytics. Contact and privacy requests by email.", "Leia sem criar conta. Preferências ficam locais. O cadastro público está disponível. Sem analytics publicitário. Contato e solicitações de privacidade por e-mail.", "Lee sin crear cuenta. Las preferencias quedan en tu dispositivo. El registro público está disponible. Sin analytics publicitario. Contacto y solicitudes de privacidad por correo.")[language]}</p>
        <a href="mailto:christiansilva.dev@outlook.com">{text("Privacy contact", "Contato de privacidade", "Contacto de privacidad")[language]} ↗</a>
        <button type="button" className="privacy-storage-button" onClick={openStorageSettings}>{text("Manage local storage", "Gerenciar armazenamento local", "Gestionar almacenamiento local")[language]} ↗</button>
      </aside>
      <article>
        {sections.slice(0, 3).map(section => <section key={section.title.en}><h2>{section.title[language]}</h2><p>{section.body[language]}</p></section>)}
        <section id="storage"><h2>{text("Cookies and local storage", "Cookies e armazenamento local", "Cookies y almacenamiento local")[language]}</h2>
          <p>{text("The application does not create its own cookies; it uses localStorage. The theme key stores light/dark mode, portfolio_lang stores language, and portfolio_storage_choices stores only the two remembering choices and their format version. These preference values stay until changed or removed. Authentication uses separate Supabase session storage. These controls do not delete account data, provider logs, development drafts or data belonging to other sites.", "A aplicação não cria cookies próprios; utiliza localStorage. A chave theme guarda o modo claro/escuro, portfolio_lang guarda o idioma e portfolio_storage_choices guarda apenas as duas escolhas de memorização e a versão do formato. Esses valores permanecem até serem alterados ou removidos. A autenticação usa armazenamento de sessão separado do Supabase. Estes controles não excluem dados da conta, logs dos fornecedores, rascunhos de desenvolvimento ou dados de outros sites.", "La aplicación no crea cookies propios; utiliza localStorage. La clave theme guarda el modo claro/oscuro, portfolio_lang guarda el idioma y portfolio_storage_choices conserva solo las dos elecciones y la versión del formato. Estos valores permanecen hasta cambiarse o borrarse. La autenticación utiliza almacenamiento separado de Supabase. Estos controles no eliminan cuentas, registros de proveedores, borradores de desarrollo ni datos de otros sitios.")[language]}</p>
          <p>{text("Turning off remembering removes that saved value and keeps the current display for this visit. Clearing saved preferences turns both choices off; the minimal choices record remains so the application respects that decision. Sign-out in this panel is separate and ends this session, not other devices; already-issued access tokens may remain valid until expiry. These settings are not consent to analytics or advertising. Providers may use their own operational mechanisms under their terms.", "Desativar a memorização remove o valor salvo e mantém a exibição atual nesta visita. Limpar preferências desativa as duas opções; o registro mínimo das escolhas permanece para que a aplicação respeite essa decisão. O logout deste painel é separado e encerra esta sessão, não outros dispositivos; tokens de acesso já emitidos podem continuar válidos até expirar. Estas opções não são consentimento para analytics ou publicidade. Fornecedores podem usar mecanismos operacionais próprios, sujeitos aos seus termos.", "Desactivar recordar elimina el valor guardado y mantiene la visualización durante esta visita. Borrar preferencias desactiva ambas opciones; el registro mínimo se mantiene para respetar la decisión. Cerrar sesión desde este panel es una acción separada y no afecta otros dispositivos; los tokens emitidos pueden ser válidos hasta caducar. Estas opciones no son consentimiento para analytics ni publicidad. Los proveedores pueden usar sus propios mecanismos operativos según sus términos.")[language]}</p>
          <button type="button" className="privacy-storage-button" onClick={openStorageSettings}>{text("Open storage settings", "Abrir preferências de armazenamento", "Abrir preferencias de almacenamiento")[language]} ↗</button>
        </section>
        <section><h2>{text("Messages", "Mensagens", "Mensajes")[language]}</h2><p>{contactFormEnabled
          ? text("When the contact form is enabled, your name, email and message are sent to a Supabase Edge Function and relayed through Brevo to the portfolio owner. The portfolio database does not store message contents. A salted hash of the request IP is used for abuse rate limiting; stale rate-limit records are pruned on later contact requests. Cloudflare Turnstile verifies the submission. Do not include sensitive or confidential information.", "Quando o formulário está ativo, nome, e-mail e mensagem são enviados a uma Supabase Edge Function e encaminhados pelo Brevo ao responsável pelo portfólio. O banco do portfólio não armazena o conteúdo das mensagens. Um hash com salt do IP da solicitação é usado para limitar abuso; registros antigos do limitador são removidos em solicitações posteriores. O Cloudflare Turnstile verifica o envio. Não inclua informações sensíveis ou confidenciais.", "Cuando el formulario está activo, el nombre, correo y mensaje se envían a una Supabase Edge Function y se transmiten mediante Brevo al responsable del portafolio. La base de datos del portafolio no almacena el contenido. Se usa un hash con salt de la IP para limitar abusos; los registros antiguos se depuran en solicitudes posteriores. Cloudflare Turnstile verifica el envío. No incluyas información sensible ni confidencial.")[language]
          : text("The website form is not enabled in this build. The email link opens your email application; this website does not receive a message through a form.", "O formulário do site não está ativo nesta versão. O link de e-mail abre seu aplicativo de correio; este site não recebe mensagens por formulário.", "El formulario del sitio no está activo en esta versión. El enlace abre tu aplicación de correo; este sitio no recibe mensajes mediante un formulario.")[language]}</p>
          {contactFormEnabled && <a href="https://www.brevo.com/legal/privacypolicy/" target="_blank" rel="noopener noreferrer">Brevo privacy notice ↗</a>}
        </section>
        {captchaSiteKey && <section><h2>{text("Abuse prevention", "Prevenção de abuso", "Prevención de abuso")[language]}</h2><p>{text("Cloudflare Turnstile verifies contact and configured authentication requests, and may process connection and device information. The contact Edge Function validates each token server-side with Cloudflare; Supabase Auth validates authentication tokens when CAPTCHA is enabled there. A frontend widget alone is not protection.", "O Cloudflare Turnstile verifica solicitações de contato e de autenticação quando configurado, e pode tratar informações de conexão e dispositivo. A Edge Function de contato valida o token no servidor com a Cloudflare; o Supabase Auth valida tokens de autenticação quando o CAPTCHA está habilitado lá. Um widget no frontend sozinho não é proteção.", "Cloudflare Turnstile verifica solicitudes de contacto y autenticación cuando está configurado, y puede tratar datos de conexión y dispositivo. La Edge Function valida cada token con Cloudflare; Supabase Auth valida los tokens de autenticación cuando el CAPTCHA está habilitado allí. El widget por sí solo no protege.")[language]}</p></section>}
        {sections.slice(3).map(section => <section key={section.title.en}><h2>{section.title[language]}</h2><p>{section.body[language]}</p></section>)}
        <nav className="privacy-links"><Link to="/">{text("Back to portfolio", "Voltar ao portfólio", "Volver al portafolio")[language]} ↗</Link><a href="https://www.gov.br/anpd/pt-br" target="_blank" rel="noopener noreferrer">ANPD ↗</a></nav>
      </article>
    </div>
  </main></>;
}
