import { useEffect } from "react";
import { Link } from "react-router-dom";
import NavBar from "../../components/NavBar/NavBar";
import { useLanguage } from "../../context/LanguageContext";
import { text } from "../../data/editorial";
import { activeContactEndpoint, captchaSiteKey } from "../../lib/securityConfig";
import "../../components/ProjectStory/ProjectStory.css";
import "../profile/Profile.css";
import "./Privacy.css";

const sections = [
  { title: text("Who is responsible", "Quem é responsável", "Quién es responsable"), body: text(
    "Christian Silva is responsible for the use of personal data in this portfolio. For privacy requests, contact christiansilva.dev@outlook.com. This notice describes the current implementation; it is not a claim of a completed legal certification.",
    "Christian Silva é responsável pelo uso de dados pessoais neste portfólio. Para solicitações de privacidade, use christiansilva.dev@outlook.com. Este aviso descreve a implementação atual; não representa uma certificação jurídica de conformidade.",
    "Christian Silva es responsable del uso de datos personales en este portafolio. Para solicitudes de privacidad, escribe a christiansilva.dev@outlook.com. Este aviso describe la implementación actual; no representa una certificación jurídica de cumplimiento.") },
  { title: text("Browsing and preferences", "Navegação e preferências", "Navegación y preferencias"), body: text(
    "You can read projects and articles without an account. The browser saves your chosen theme and language locally, until you change them or clear site storage. GitHub Pages and Supabase may process connection information, such as IP address and request logs, to deliver and protect their services.",
    "Você pode ler projetos e artigos sem criar uma conta. O navegador salva tema e idioma localmente, até você alterá-los ou limpar os dados do site. GitHub Pages e Supabase podem tratar informações de conexão, como endereço IP e registros de requisições, para entregar e proteger seus serviços.",
    "Puedes leer proyectos y artículos sin crear una cuenta. El navegador guarda tema e idioma localmente hasta que los cambies o borres los datos del sitio. GitHub Pages y Supabase pueden tratar información de conexión, como dirección IP y registros de solicitudes, para prestar y proteger sus servicios.") },
  { title: text("Account and authentication", "Conta e autenticação", "Cuenta y autenticación"), body: text(
    "Public registration remains available. When you create an account, your name and email are processed through Supabase Auth and the profile database. Passwords are sent over HTTPS to Supabase Auth and hashed by that service; this application does not keep password hashes. An authenticated session is persisted in browser storage until sign-out or removal of local data; server-side token validity is managed separately by Supabase. Do not use a shared device without signing out.",
    "O cadastro público permanece disponível. Ao criar uma conta, nome e e-mail são tratados pelo Supabase Auth e pelo banco de perfis. Senhas são enviadas por HTTPS ao Supabase Auth e transformadas em hash por esse serviço; esta aplicação não mantém hashes de senha. A sessão autenticada é persistida no armazenamento do navegador até o logout ou a remoção dos dados locais; a validade dos tokens no servidor é gerenciada separadamente pelo Supabase. Evite deixar uma sessão aberta em um dispositivo compartilhado.",
    "El registro público permanece disponible. Al crear una cuenta, nombre y correo se tratan mediante Supabase Auth y la base de perfiles. Las contraseñas se envían por HTTPS a Supabase Auth, que almacena sus hashes; esta aplicación no conserva hashes de contraseñas. La sesión se guarda en el navegador hasta cerrar sesión o borrar los datos locales; la validez de los tokens en el servidor se gestiona por separado en Supabase. No dejes una sesión abierta en un dispositivo compartido.") },
  { title: text("No behavioral analytics", "Sem análise comportamental", "Sin análisis de comportamiento"), body: text(
    "The application does not include advertising trackers or send its performance diagnostics to an analytics service. The optional performance panel stays on your device. This does not mean that hosting providers keep no operational logs. The pedal lab is a mathematical simulation and does not access hardware, camera or microphone.",
    "A aplicação não inclui rastreadores de publicidade nem envia seus diagnósticos de desempenho a um serviço de analytics. O painel opcional permanece no seu dispositivo. Isso não significa que os provedores de hospedagem não mantenham registros operacionais. O laboratório de pedais é uma simulação matemática e não acessa hardware, câmera ou microfone.",
    "La aplicación no incluye rastreadores publicitarios ni envía sus diagnósticos de rendimiento a un servicio de analytics. El panel opcional permanece en tu dispositivo. Esto no significa que los proveedores de alojamiento no conserven registros operativos. El laboratorio de pedales es una simulación matemática y no accede a hardware, cámara ni micrófono.") },
  { title: text("Providers and international processing", "Fornecedores e tratamento internacional", "Proveedores y tratamiento internacional"), body: text(
    "GitHub provides hosting; Supabase provides public content, authentication and profile storage. Email messages use the sender's email service and the recipient's Outlook mailbox. Providers may process data outside Brazil. The project region, applicable transfer safeguards and provider retention periods still need operational verification; this notice does not assert Brazilian-only storage. External links open another service under its own privacy terms.",
    "GitHub fornece hospedagem; Supabase fornece conteúdo público, autenticação e armazenamento de perfis. Mensagens de e-mail usam o serviço do remetente e a caixa Outlook do destinatário. Fornecedores podem tratar dados fora do Brasil. A região do projeto, as garantias aplicáveis à transferência e os prazos de retenção dos fornecedores ainda precisam de verificação operacional; este aviso não afirma armazenamento exclusivo no Brasil. Links externos levam a outro serviço, sujeito aos seus próprios termos de privacidade.",
    "GitHub ofrece alojamiento; Supabase ofrece contenido público, autenticación y almacenamiento de perfiles. Los correos utilizan el servicio del remitente y el buzón Outlook del destinatario. Los proveedores pueden tratar datos fuera de Brasil. La región del proyecto, las garantías de transferencia y los plazos de conservación aún requieren verificación operativa; este aviso no afirma almacenamiento exclusivo en Brasil. Los enlaces externos llevan a otro servicio con sus propios términos de privacidad.") },
  { title: text("Retention and current limits", "Retenção e limites atuais", "Conservación y límites actuales"), body: text(
    "The current code does not automatically delete accounts or correspondence after a fixed period. Local preferences remain until browser storage is cleared. Retention periods and the lawful basis for each processing activity are being finalized with the operator; no automatic purge or fixed supplier-log deadline is promised. Previously published content can remain in static pages until a new deployment replaces it.",
    "O código atual não elimina automaticamente contas ou correspondências após um período fixo. Preferências locais permanecem até a limpeza do armazenamento do navegador. Os prazos de retenção e a base legal de cada atividade estão em definição com o responsável; não há promessa de descarte automático nem de um prazo fixo para logs dos fornecedores. Conteúdo antes publicado pode permanecer nas páginas estáticas até que um novo deploy o substitua.",
    "El código actual no elimina automáticamente cuentas o correspondencia después de un plazo fijo. Las preferencias locales permanecen hasta borrar el almacenamiento del navegador. Los plazos y la base legal de cada actividad se están definiendo con el responsable; no se promete borrado automático ni un plazo fijo para los registros de proveedores. El contenido publicado puede permanecer en páginas estáticas hasta un nuevo despliegue.") },
  { title: text("Your requests", "Suas solicitações", "Tus solicitudes"), body: text(
    "You can request confirmation of processing, access, correction and deletion where applicable, or ask about sharing and retention, by email with the subject “Privacy request”. Identity may need proportionate verification before account data are disclosed or deleted. This is a manual request channel, not an automatic account-deletion button. Never send a password, session token, authenticator secret or one-time code.",
    "Você pode solicitar confirmação de tratamento, acesso, correção e eliminação quando aplicável, ou perguntar sobre compartilhamento e retenção, por e-mail com o assunto “Solicitação de privacidade”. Pode ser necessária uma verificação proporcional de identidade antes de fornecer ou eliminar dados de uma conta. Este é um canal de solicitação manual, não um botão de exclusão automática. Nunca envie senha, token de sessão, chave de autenticador ou código de uso único.",
    "Puedes solicitar confirmación de tratamiento, acceso, rectificación y eliminación cuando corresponda, o preguntar sobre compartir y conservar datos, por correo con el asunto “Solicitud de privacidad”. Puede requerirse verificación proporcional de identidad antes de entregar o borrar datos de una cuenta. Este canal es manual, no un botón de eliminación automática. Nunca envíes contraseñas, tokens de sesión, claves de autenticador ni códigos de un solo uso.") },
];

export default function Privacy() {
  const { language } = useLanguage();
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); }, []);
  return <><NavBar /><main id="main-content" tabIndex={-1} className="editorial-page privacy-page">
    <header className="editorial-page-header"><p className="story-eyebrow">PRIVACY / 01</p>
      <h1>{text("Clear about your data.", "Clareza sobre seus dados.", "Claridad sobre tus datos.")[language]}</h1>
      <p>{text("Privacy notice · Updated September 28, 2026", "Aviso de privacidade · Atualizado em 28 de setembro de 2026", "Aviso de privacidad · Actualizado el 28 de septiembre de 2026")[language]}</p>
    </header>
    <div className="privacy-reading">
      <aside className="privacy-summary"><p className="story-eyebrow">{text("IN SHORT", "EM RESUMO", "EN RESUMEN")[language]}</p>
        <p>{text("Read without an account. Preferences stay local. Public registration is available. No advertising analytics. Contact and privacy requests by email.", "Leia sem criar conta. Preferências ficam locais. O cadastro público está disponível. Sem analytics publicitário. Contato e solicitações de privacidade por e-mail.", "Lee sin crear cuenta. Las preferencias quedan en tu dispositivo. El registro público está disponible. Sin analytics publicitario. Contacto y solicitudes de privacidad por correo.")[language]}</p>
        <a href="mailto:christiansilva.dev@outlook.com">{text("Privacy contact", "Contato de privacidade", "Contacto de privacidad")[language]} ↗</a>
      </aside>
      <article>
        {sections.slice(0, 3).map(section => <section key={section.title.en}><h2>{section.title[language]}</h2><p>{section.body[language]}</p></section>)}
        <section><h2>{text("Messages", "Mensagens", "Mensajes")[language]}</h2><p>{activeContactEndpoint
          ? text("The configured contact form sends your name, email and message to Formspree to deliver your request. Read its privacy notice before sending. Do not include sensitive or confidential information.", "O formulário configurado envia nome, e-mail e mensagem ao Formspree para entregar sua solicitação. Consulte o aviso de privacidade desse fornecedor antes de enviar. Não inclua informações sensíveis ou confidenciais.", "El formulario configurado envía nombre, correo y mensaje a Formspree para entregar tu solicitud. Consulta su aviso de privacidad antes de enviar. No incluyas información sensible ni confidencial.")[language]
          : text("No web-form delivery endpoint is configured in this version. The email link opens your email application; this website does not receive the message body through a form.", "Esta versão não possui um endpoint de envio de formulário configurado. O link de e-mail abre seu aplicativo de correio; este site não recebe o conteúdo da mensagem por um formulário.", "Esta versión no tiene configurado un endpoint de formulario. El enlace abre tu aplicación de correo; este sitio no recibe el contenido mediante un formulario.")[language]}</p>
          {activeContactEndpoint && <a href="https://formspree.io/legal/privacy-policy/" target="_blank" rel="noopener noreferrer">Formspree ↗</a>}
        </section>
        {captchaSiteKey && <section><h2>{text("Abuse prevention", "Prevenção de abuso", "Prevención de abuso")[language]}</h2><p>{text("The authentication dialog loads Cloudflare Turnstile to verify requests. Cloudflare may process connection and device information for this check. Supabase validates the token when CAPTCHA is enabled in the project; a frontend widget alone is not protection.", "A janela de autenticação carrega Cloudflare Turnstile para verificar solicitações. A Cloudflare pode tratar informações de conexão e dispositivo nessa verificação. O Supabase valida o token quando CAPTCHA está habilitado no projeto; um widget no frontend, sozinho, não é proteção.", "El diálogo de autenticación carga Cloudflare Turnstile para verificar solicitudes. Cloudflare puede tratar información de conexión y dispositivo. Supabase valida el token cuando CAPTCHA está habilitado en el proyecto; un widget por sí solo no es protección.")[language]}</p></section>}
        {sections.slice(3).map(section => <section key={section.title.en}><h2>{section.title[language]}</h2><p>{section.body[language]}</p></section>)}
        <nav className="privacy-links"><Link to="/">{text("Back to portfolio", "Voltar ao portfólio", "Volver al portafolio")[language]} ↗</Link><a href="https://www.gov.br/anpd/pt-br" target="_blank" rel="noopener noreferrer">ANPD ↗</a></nav>
      </article>
    </div>
  </main></>;
}
